<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

#### Input Layer: Input layer consists of number of units and each unit represents individual features from the dataset that will be passed to the model.
#### Hidden Layer: Hidden layer is a layer to which all units from input layer are connected. Output (input multiplied to the assigned weight of this input with added bias) from input layer is transfered via that connection to hidden layer for further computation.
#### Output Layer: Output layer consists of units which represent possible categories for the output. For example, if the task to recognize images with apple and strawberry, there will be two possible outcomes.
#### Neuron: is a one of the units in the layers which hold the number between 0 and 1.
#### Weight: parameter, positive or negative number, assigned to each of the connections between neurons.
#### Activation Function: Is function that computes input values in hidden layer. It can be any function, such as sigmoid, ReLU and others.
#### Node Map: is a flow chart in that it shows the path from inputs to outputs
#### Perceptron: is like a binary linear function, linear classifier that can decide if input belongs to the particular class.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### First, input layer takes features from dataset as an inputs. Each input multiplies by weight, sums all of these products up and adds bias, then transfers to hidden layer for further computation. Before passing to the last output layer, data may go through the ativation function in each neuron, which can be sigmoid, ReLU and others before it outputs the result. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [56]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [57]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [65]:
df.T

0  1  2  3
x1  0  1  0  1
x2  0  0  1  1
y   1  1  1  0

In [58]:
correct_outputs = [[0],[1],[0],[1]]

In [6]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx*(1-sx)

In [71]:
weights = 2 * np.random.random((3,1)) - 1
weights

array([[ 0.46026931],
       [-0.11424282],
       [ 0.85483923]])

In [72]:
# Weighted sum 
weighted_sum = np.dot(df, weights)
weighted_sum

array([[0.85483923],
       [1.31510855],
       [0.74059641],
       [0.34602649]])

In [73]:
# Activate
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.7015813 ],
       [0.78836675],
       [0.67712626],
       [0.58565368]])

In [74]:
# Cac error
error = correct_outputs - activated_outputs
error

array([[-0.7015813 ],
       [ 0.21163325],
       [-0.67712626],
       [ 0.41434632]])

In [75]:
adjustments = error*sigmoid_derivative(weighted_sum)
adjustments

array([[-0.14688655],
       [ 0.03530987],
       [-0.1480376 ],
       [ 0.10054671]])

In [76]:
# Update the Weights
weights = weights + np.dot(df.T, adjustments)
weights

array([[ 0.59612589],
       [-0.16173372],
       [ 0.59522495]])

In [77]:
print("Weights after training")
print(weights)

print("Output after training")
print(activated_outputs)

Weights after training
[[ 0.59612589]
 [-0.16173372]
 [ 0.59522495]]
Output after training
[[0.7015813 ]
 [0.78836675]
 [0.67712626]
 [0.58565368]]


In [78]:
# put everything together

for i in range(10000):
    
    # sums of products df/weights
    weighted_sum = np.dot(df, weights)
    
    # sums go through activation function sigmoid
    activated_output = sigmoid(weighted_sum)
    
    # calculate error 
    error = correct_outputs - activated_output
    
    # adjust weights based on error
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # update weights
    weights += np.dot(df.T, adjustments)

print("Weights after training")
print(weights)
print("Output after training")
print(activated_output)

Weights after training
[[ 8.98993288]
 [-1.40805855]
 [-4.40715795]]
Output after training
[[0.01204357]
 [0.98987653]
 [0.00297315]
 [0.99949061]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [24]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [27]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
target = 'Outcome'

X = diabetes[feats]
y = diabetes[target]

In [39]:
X.shape[1]

8

In [54]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx*(1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples] 
        """

        # Randomly Initialize Weights
           
        # Activate!

        # Cac error

        # Update the Weights

        
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]
    
    
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?