<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

1. Binary Cross-Entropy Loss function is the most suitable to predict 1/0. 

2. The loss function is used to optimize the model. A metric is used to check the performance of the model.

3. Adam optimizer can be used instead of sgd. it updates weights based on training data and it has faster performance.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = { 'x1': [0,0,1,0,1,1,0],
         'x2': [0,1,0,1,0,1,0],
         'x3': [1,1,1,0,0,1,0],
         'y':  [0,1,1,1,1,0,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [47]:
df.shape

(7, 4)

In [127]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [107]:
model = Sequential([
    Dense(3, activation='sigmoid', input_dim=3),
    Dense(4, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

In [108]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [61]:
features = df.columns[1:]
targ = df.columns[:1]

In [62]:
X = df[features].values
y = df[targ].values

In [63]:
X

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0],
       [0, 0, 0]])

In [64]:
y

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0]])

In [115]:
results = model.fit(X,y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5952 - acc: 0.8571
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5949 - acc: 0.8571
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5946 - acc: 0.8571
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5943 - acc: 0.8571
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5941 - acc: 0.8571
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5938 - acc: 0.8571
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5935 - acc: 0.8571
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5932 - acc: 0.8571
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5929 - acc: 0.8571
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5926 - acc: 0.8571
Epoch 11/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5923 

### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

#### The reason of the disparity is because the classes in XOR are not linearly separable.

#### The multilayer perceptron is the solution for XOR problem

In [ ]:
### Compare 

## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [116]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [117]:
# input image dimensions
img_rows, img_cols = 28, 28

In [118]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [119]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [123]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [121]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [125]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [175]:
##### Your Code Here #####
model = Sequential([
    Dense(1000, activation='softmax'),
    Dense(2)
])


In [176]:
# compile
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [177]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1366 - accuracy: 0.1066
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0318 - accuracy: 0.2107
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0267 - accuracy: 0.7959
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0217 - accuracy: 0.8231
Epoch 5/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0197 - accuracy: 0.7098
Epoch 6/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0180 - accuracy: 0.8276
Epoch 7/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0174 - accuracy: 0.5115
Epoch 8/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0140 - accuracy: 0.4088
Epoch 9/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0133 - accuracy: 0.4447
Epoch 10/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.011

In [179]:
scores = model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0193 - accuracy: 0.8991


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?